version: 0.2
phases:
  pre_build:
    commands:
    - $(aws ecr get-login --no-include-email)
    - TAG="$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | head -c 8)"
    - IMAGE_URI="cf-sp-repos-1rzo4st5w6em8:${TAG}"
  build:
    commands:
    - docker build --tag "$IMAGE_URI" .
  post_build:
    commands:
    - docker push "$IMAGE_URI"
    - printf '[{"name":"simple-app","imageUri":"%s"}]' "$IMAGE_URI" > images.json
artifacts:
  files: images.json